name: Run tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Build env
        run: make build-env
      - name: Run unit tests
        run: run-unit-test
